### ISSUE TITLE
_headers file is not correctly generated for stylesheets

### ISSUE THREAD

**Issue by matsp** [koole/netlify-push-webpack-plugin#4]
This plugin is generating the following for stylesheets:

```
/*
  Link: </0.06afe44df035a8afa4de.css>; rel=preload; as=stylesheet
```

Server push is not working with this definition - it should be:

```
/*
  Link: </0.06afe44df035a8afa4de.css>; rel=preload; as=style
```

Ref: https://www.w3.org/TR/preload/#server-push-http-2

**Comment by koole** [comment]
You are indeed correct. Your fix has been merged, thanks!
